name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y googletest libgtest-dev build-essential gcovr
    - name: Build tests
      run: g++ -std=c++17 -I/usr/include/gtest -L/usr/lib/x86_64-linux-gnu tests.cpp -o tests.out -lgtest -lpthread
    - name: Run tests
      run: ./tests.out