name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev cmake

    - name: Build GoogleTest
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Compile tests
      run: g++ -std=c++17 -I/usr/include/gtest tests.cpp -o tests.out -lgtest -lpthread

    - name: Run tests
      run: ./tests.out